### ISSUE TITLE
Password in url 

### ISSUE THREAD

**Issue by flickerfly** [exitnode/qrzlogger#1]
Neat project! Is there a way to pass credentials without putting them in the url? 

https://github.com/exitnode/qrzlogger/blob/9b5309b9f0c4e35686a9c83c2b8cac1a7dd7b845/qrzlogger.py#L112

**Comment by exitnode** [comment]
Thank you - you are absolutely right! It is now fixed with #https://github.com/exitnode/qrzlogger/commit/235275eb7545190691ec1d1585fad0c9c632902d
Are you the Redditor I mentioned in the commit comment?

**Comment by exitnode** [comment]
fixed

**Comment by flickerfly** [comment]
@exitnode Thanks, I'm not that redditor.
